### ISSUE TITLE
Helpop nie wyswietla komend

### ISSUE THREAD

**Issue by GTMagnez** [GTMero/GT-Craft-Bledy#2]
1. __Magnez__
2. 14:45
3. Podczas wpisywania komendy helpop, wyswietla sie inna wwiadomość niżż opisania w skrypcie
4. Udało sie
5.
![image](https://user-images.githubusercontent.com/128172431/226179247-8d420953-8c32-45a2-a7eb-0c71bef67d7d.png)

**Comment by GTMero** [comment]
Zostanie to poprawione w następnym patchu.
